### ISSUE TITLE
taxa_barplot: Argument ntoplot > 10 changes the color pallete

### ISSUE THREAD

**Issue by JoaoMiranda96** [jbisanz/qiime2R#41]
Hello everyone,

I'm using the `taxa_barplot` to make stacked barplots for different taxon levels. When I use the default `ntoplot` (that limits to 10 taxa) the color pallete is great, with the reminder colored in grey, that is a pattern that I want to keep for the others barplots.

But when I use` ntoplot` with more taxa (I tested with ntoplot = 12 or ntoplot = 15) the color pallete changes. So how can I keep the  default color pallete ? Here are the images for comparasion.

![Stacked_barplot_Family](https://user-images.githubusercontent.com/92695575/151012507-38e284ab-0d05-4a31-b61b-afef64ebab7e.png)
![Stacked_barplot_Family_12](https://user-images.githubusercontent.com/92695575/151012533-5fb6ccc1-5702-4a38-afea-3a3a810038fd.png)

**Comment by jbisanz** [comment]
Hi Joao, the color scale for <=10 features was my personal selection. If you want a custom scale you can add the following to your code:
```
taxa_barplot(...) + scale_fill_manual(values=c("darkblue","olivedrab",...)) 
```

I only provided up to 10 colors because I find it very difficult to interpret a stacked barplot with more than 10 taxa.

PS: if you want to add to the default color scale, this is it:
```
  q2r_palette<-c(
    "blue4",
    "olivedrab",
    "firebrick",
    "gold",
    "darkorchid",
    "steelblue2",
    "chartreuse1",
    "aquamarine",
    "yellow3",
    "coral",
    "grey"
  )
```
